# realestate
from app import db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from app import login
from hashlib import md5
from time import time
import jwt
from app import app


class User (db.Model):
    id =db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(64), index=True,unique=True)
    email =db.Column(db.String(120),index=True, unique=True)
    password_hash = db.Column(db.String(128))



 class Buyer(db.Model):
     id=db.Column(db.Integer,primary_key=True)
     Name = db.Column(db.String(64),index=True)
     Phone_number=db.Column(db.Integer(12))
     Address = db.Column(db.String(60))
     Email =db.Column(db.String(120),index=True,unique=True)
     Company =db.Column(db.String(30),index=True)
     Job = db.Column(db.String(30)index=True)
     Title = db.Column(db.String(30)index=True)
     Refered_by=db.Column(db.String(30)index=True)
     Contact_info=db.Column(db.String(25)index=True)
     Nickname = db.Column(db.String(25)index=True)
     Website =db.Column(db.String(50)index=True,unique=True)
     Reffered = db.Column(db.String(30)index=True)
     Intent=db.Column(db.String(20))
     Notes = Column(db.String(1000))
     States = db.Column(db.String(25))
     Cities = db.Column(db.String(20))
     Counties = db.Column(db.String(25))
     Countries =db.Column(db.String(20))
     Type = db.Column(db.String(30))
     Price_buillding_area =db.Column(db.Integer(10))
     Stories = db.Column(db.Integer(15))
     Units=db.Column(db.Interger(10))
     Tax = db.Column(db.Integer(10))
     Sale_date=db.Column(db.Integer(10))
     Sale_amount = db.Column(db.Integer(10))
     Price_per_building_area = db.Column(db.Integer(10))
     Price_per_unit = db.Column(db.Integer(10))
     Price_per_square_foot = db.Column(db.Integer(10))
     Far = db.Column(db.Integer(10))
     Irr = db.Column(db.Integer(10))
     cap = db.Column(db.Integer(10))
     Operating_income =db.Column(db.Integer(10))
     Gross_income = db.Column(db.Integer(10))
     Operating_cost = db.Column(db.Integer(10))
     Debt =db.Column(db.Integer(10))
     Equity = db.Column(db.Integer(10))
     Comission = db.Column(db.Integer(10))
     Owners_details = db.Column(db.String(100))
     Financing = db.Column(db.Integer(15))

 class Properties(db.Model):
 	 id=db.Column(db.Integer,primary_key=True)
     Name = db.Column(db.String(64),index=True)
     Phone_number=db.Column(db.Integer(12))
     Address = db.Column(db.String(60))
     Email =db.Column(db.String(120),index=True,unique=True)
     Company =db.Column(db.String(30),index=True)
     Job = db.Column(db.String(30)index=True)
     Title = db.Column(db.String(30)index=True)
     Refered_by=db.Column(db.String(30)index=True)
     Contact_info=db.Column(db.String(25)index=True)
     Nickname = db.Column(db.String(25)index=True)
     Website =db.Column(db.String(50)index=True,unique=True)
     Reffered = db.Column(db.String(30)index=True)
     Intent = db.Column(db.String(20))
     Notes = Column(db.String(1000))
     State = db.Column(db.String(25))
     City = db.Column(db.String(20))
     County = db.Column(db.String(25))
     Country = db.Column(db.String(20))
     Type = db.Column(db.String(30))
     Price_buillding_area =db.Column(db.Integer(10))
     Stories = db.Column(db.Integer(15))
     Units = db.Column(db.Interger(10))
     Tax = db.Column(db.Integer(10))
     Sale_date=db.Column(db.Integer(10))
     Sale_amount = db.Column(db.Integer(10))
     Price_per_building_area = db.Column(db.Integer(10))
     Price_per_unit = db.Column(db.Integer(10))
     Price_per_square_foot = db.Column(db.Integer(10))
     Far = db.Column(db.Integer(10))
     Irr = db.Column(db.Integer(10))
     cap = db.Column(db.Integer(10))
     Operating_income =db.Column(db.Integer(10))
     Gross_income = db.Column(db.Integer(10))
     Operating_cost = db.Column(db.Integer(10))
     Debt =db.Column(db.Integer(10))
     Equity = db.Column(db.Integer(10))
     Comission = db.Column(db.Integer(10))
     Owners_details = db.Column(db.String(100))
     Financing = db.Column(db.Integer(15))

 class Developments(db.Model):
     id=db.Column(db.Integer,primary_key=True)
     Name = db.Column(db.String(64),index=True)
     Phone_number=db.Column(db.Integer(12))
     Address = db.Column(db.String(60))
     Email =db.Column(db.String(120),index=True,unique=True)
     Company =db.Column(db.String(30),index=True)
     Job = db.Column(db.String(30)index=True)
     Title = db.Column(db.String(30)index=True)
     Refered_by=db.Column(db.String(30)index=True)
     Contact_info=db.Column(db.String(25)index=True)
     Nickname = db.Column(db.String(25)index=True)
     Website =db.Column(db.String(50)index=True,unique=True)
     Reffered = db.Column(db.String(30)index=True)
     Intent=db.Column(db.String(20))
     Notes = Column(db.String(1000))
     State = db.Column(db.String(25))
     City = db.Column(db.String(20))
     County = db.Column(db.String(25))
     Country = db.Column(db.String(20))
     Type = db.Column(db.String(30))
     Buillding_area =db.Column(db.Integer(10))
     Stories = db.Column(db.Integer(15))
     Units=db.Column(db.Interger(10))
     Tax = db.Column(db.Integer(10))
     Sale_date=db.Column(db.Integer(10))
     Sale_amount = db.Column(db.Integer(10))
     Price_per_building_area = db.Column(db.Integer(10))
     Price_per_unit = db.Column(db.Integer(10))
     Price_per_square_foot = db.Column(db.Integer(10))
     Far = db.Column(db.Integer(10))
     Irr = db.Column(db.Integer(10))
     cap = db.Column(db.Integer(10))
     Operating_income =db.Column(db.Integer(10))
     Gross_income = db.Column(db.Integer(10))
     Operating_cost = db.Column(db.Integer(10))
     Debt =db.Column(db.Integer(10))
     Equity = db.Column(db.Integer(10))
     Comission = db.Column(db.Integer(10))
     Owners_details = db.Column(db.String(100))
     Land_cost =  db.Column(db.Integer(15))
     Infrastructre = db.Column(db.Integer(15))
     Construction_cost = db.Column(db.Integer(15))
     Project_management =db.Column(db.Integer(15))
     Design = db.Column(db.Integer(15))
     Profesional_fees =db.Column(db.Integer(15))
     Club_Marketing_costs = db.Column(db.Integer(15))   
     Financing_fee = db.Column(db.Integer(15))
     Intrest = db.Column(db.Integer(15))
     Contingency =db.Column(db.Integer(15))
     Subtotal_development_cost = db.Column(db.Integer(15))
     Goverment_grants = db.Column(db.Integer(15))
